services:
    
  datagerry:
    image: becongmbh/datagerry:latest
    hostname: datagerry
    depends_on:
    - db
    ports:
    - 4000:4000
    environment:
      DATAGERRY_Database_host: "db"
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - "traefik.http.routers.<unique_router_name>.rule=Host(`coolify.io`) && PathPrefix(`/`)"
      - traefik.http.routers.<unique_router_name>.entryPoints=http

  db:
    image: mongo:6.0.25
    hostname: db
    restart: unless-stopped
    volumes:
      - mongodb-data:/data/db
      - mongodb-config:/data/configdb

volumes:
  mongodb-data:
  mongodb-config:

labels:
  - traefik.enable=true
  - "traefik.http.routers.<unique_router_name>.rule=Host(`coolify.io`) && PathPrefix(`/`)"
  - traefik.http.routers.<unique_router_name>.entryPoints=http
